import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Comprehensive mapping of all encoding issues
const encodingFixes: Record<string, string> = {
  // Names with encoding issues
  'Joo Costa Madureira': 'João Costa Madureira',
  'Christoph Brnnimann': 'Christoph Brönnimann',
  'Sbastien Page': 'Sébastien Page',
  'Emmanuel Gutirrez-Corts': 'Emmanuel Gutiérrez-Cortés',
  'Kerem K?z?ltun': 'Kerem Kızıltunç',
  'Kerem K?z?ltunç': 'Kerem Kızıltunç',
  'Ivn Gonzlez Vallejo': 'Iván González Vallejo',
  'Ivan Gonzalez Vallejo': 'Iván González Vallejo',
  'Gnen Sener': 'Gönenç Sener',
  'Gonenç Sener': 'Gönenç Sener',
  
  // Company names with encoding issues
  '3 Coraes': '3 Corações',
  '3 Coraões': '3 Corações',
  'Kofola ?eskoSlovensko': 'Kofola ČeskoSlovensko',
  'Kofola ČeskoSlovensko': 'Kofola ČeskoSlovensko',
  'Kerem Kızıltunç': 'Kerem Kızıltunç',
  'Emmanuel Gutiérrez-Cortés': 'Emmanuel Gutiérrez-Cortés',
  'João Costa Madureira': 'João Costa Madureira',
  'Sébastien Page': 'Sébastien Page',
  'Gudmundur Sigurdsson': 'Gudmundur Sigurdsson',
  'Alain Lachapelle': 'Alain Lachapelle',
  'Soren Petsch': 'Soren Petsch',
  'Jairo Cesar': 'Jairo Cesar',
  'Fernando Bosch': 'Fernando Bosch',
  'Anish Azeez': 'Anish Azeez',
  'Adeel Abbasi': 'Adeel Abbasi',
  'Soumendu S': 'Soumendu S',
  'Arik Spitzer': 'Arik Spitzer',
  'Amy Aguirre': 'Amy Aguirre',
  'Jacob Harrison': 'Jacob Harrison',
  'Vivian Wu': 'Vivian Wu',
  'Joel Klooster': 'Joel Klooster',
  'Ali Rashed': 'Ali Rashed',
  'Thomas Scott': 'Thomas Scott',
  'Jussi Lemola': 'Jussi Lemola',
  'Ankit Dalal': 'Ankit Dalal',
  'Nishant Deep': 'Nishant Deep',
  'Claire Phillips': 'Claire Phillips',
  'Andrea Macchia': 'Andrea Macchia',
  
  // Additional company name fixes
  'Azul Linhas Areas Brasileiras': 'Azul Linhas Aéreas Brasileiras',
  'Deutsche Aircraft': 'Deutsche Aircraft',
  'Vesuvius Polandas Brasileiras': 'Vesuvius Poland',
  'MetsoeMyTrip.com': 'Metso',
  'AHEADSpace': 'AHEAD',
  'Elior Infusion': 'Elior',
  'Virbacnologies': 'Virbac',
  'Farma Leaders Talento': 'Farma Leaders Talento',
  'Nextdoorroup': 'Nextdoor',
  'Pythian Villa d\'Este': 'Pythian',
  'Villa d\'Este': 'Villa d\'Este',
  'Decathlon Germanyroup': 'Decathlon Germany',
  'Charles River Laboratories': 'Charles River Laboratories',
  'USA Cycling Foundation': 'USA Cycling Foundation',
  'Secret Escapes': 'Secret Escapes',
  'Loveholidays': 'Loveholidays',
  'FREENOW': 'FREENOW',
  'Rohlik Group': 'Rohlik Group',
  'AWS': 'AWS',
  'PriceTravel': 'PriceTravel',
  'Menlo College': 'Menlo College',
  '180 Medical': '180 Medical',
  'Cloudera': 'Cloudera',
  'Miniso': 'Miniso',
  'Epic Flight Academy': 'Epic Flight Academy',
  'Europcar': 'Europcar',
  'Celonic': 'Celonic',
  'Navan': 'Navan',
  'Scott Dunn': 'Scott Dunn',
  'Rubrik': 'Rubrik',
  'Flybondi.com': 'Flybondi.com',
  'Turbi': 'Turbi',
  'BAE Systems': 'BAE Systems',
  'Flock Safety': 'Flock Safety',
  'Civitatis': 'Civitatis',
  'Technimede': 'Technimede',
  'UC Rusal': 'UC Rusal',
  'Puma Energy': 'Puma Energy',
  'Red Hat': 'Red Hat',
  'Rehab Medical': 'Rehab Medical',
  'Angostura': 'Angostura',
  'Hoiana Resort': 'Hoiana Resort',
  'The Design Museum': 'The Design Museum',
  'Turkish Airlines': 'Turkish Airlines',
  'Mathnasium': 'Mathnasium',
  'Vueling Airlines': 'Vueling Airlines',
  'MBDA': 'MBDA',
  'METRO Bulgaria': 'METRO Bulgaria',
  'Veristat': 'Veristat',
  'Exela Technologies': 'Exela Technologies',
  'Eurocontrol': 'Eurocontrol',
  'Riya': 'Riya',
  'Cinergy': 'Cinergy',
  'Abzena': 'Abzena',
  'Innergex': 'Innergex',
  'Varo Energy': 'Varo Energy',
  'Wireless Vision': 'Wireless Vision',
  'Qorval Partners': 'Qorval Partners',
  'Quantumscape': 'Quantumscape',
  'Wavestone': 'Wavestone',
  'Isomorphic Labs': 'Isomorphic Labs',
  'The Aerospace Corporation': 'The Aerospace Corporation',
  'Nadro': 'Nadro',
  'Air Astana': 'Air Astana',
  'Cemair': 'Cemair',
  'Newfire': 'Newfire',
  'Salesloft': 'Salesloft',
  'ESP Softtech': 'ESP Softtech',
  'Mantel': 'Mantel',
  'Logic Fruit': 'Logic Fruit',
  'Leoforce': 'Leoforce',
  'CompanyCam': 'CompanyCam',
  'McKesson': 'McKesson',
  'Covalto': 'Covalto',
  'Creative Planning': 'Creative Planning',
  'City National': 'City National',
  'Venturesoft': 'Venturesoft',
  'Nokia': 'Nokia',
  'Carta': 'Carta',
  'The Jackson Laboratory': 'The Jackson Laboratory',
  'ControlCase': 'ControlCase',
  'ERGOMED': 'ERGOMED',
  'Neste': 'Neste',
  'SAIC': 'SAIC',
  'Manolo Blahnik': 'Manolo Blahnik',
  'Loft Orbital': 'Loft Orbital',
  'Westcare Foundation': 'Westcare Foundation',
  'Layr': 'Layr',
  'HPCL Mittal': 'HPCL Mittal',
  'Pharmeasy': 'Pharmeasy',
  'Walmart Mexico & Central America': 'Walmart Mexico & Central America',
  'GEOTAB': 'GEOTAB',
  'Leaf Home': 'Leaf Home',
  'TTEC': 'TTEC',
  'Amentum': 'Amentum',
  'Boeing': 'Boeing',
  'Vertiv': 'Vertiv',
  'GPRS': 'GPRS',
  'Microsoft': 'Microsoft',
  'Sheetz': 'Sheetz',
  'Sovos': 'Sovos',
  'Dexian': 'Dexian',
  'Wasabi Technologies': 'Wasabi Technologies',
  'Babcock': 'Babcock',
  'EaseMyTrip.com': 'EaseMyTrip.com',
  'Capella Space': 'Capella Space',
  'IP Infusion': 'IP Infusion',
  'UPSA': 'UPSA',
  'Weave': 'Weave',
  'Roadchef': 'Roadchef',
  'Virbac': 'Virbac',
  'West African Resources': 'West African Resources',
  'Vesuvius Poland': 'Vesuvius Poland',
  'Metso': 'Metso',
  'AHEAD': 'AHEAD',
  'Elior': 'Elior',
  'Ceribell': 'Ceribell',
  'Lark': 'Lark',
  'Clarks': 'Clarks',
  'Saab': 'Saab',
  'Q2': 'Q2',
  'JP Morgan': 'JP Morgan',
  'Bright Horizons': 'Bright Horizons',
  'Truist': 'Truist',
  'HealthEdge': 'HealthEdge',
  'Pet Madness': 'Pet Madness',
  'American Staffing Association': 'American Staffing Association',
  'Milrem Robotics': 'Milrem Robotics',
  'Nvidia': 'Nvidia',
  'Experimental Group': 'Experimental Group',
  'Rinnai America': 'Rinnai America',
  'Juniper Networks': 'Juniper Networks',
  'Cellectis': 'Cellectis',
  'Re Sustainability': 'Re Sustainability',
  'Humacyte': 'Humacyte',
  'Satguru Travel and Tourism Services': 'Satguru Travel and Tourism Services',
  'Kona Ice': 'Kona Ice',
  'Cribl': 'Cribl',
  'Blue Jet': 'Blue Jet',
  'Corpuls': 'Corpuls',
  'Giornale': 'Giornale',
  'LaunchDarkly': 'LaunchDarkly',
  'Emirates Gold Aluminium': 'Emirates Gold Aluminium',
  'Acerinox': 'Acerinox',
  'Trustedhousesitters.com': 'Trustedhousesitters.com',
  'Footasylum': 'Footasylum',
  'TechCXO': 'TechCXO',
  'Kisna': 'Kisna',
  'Siemens': 'Siemens',
  'Flosports': 'Flosports',
  'Tradeverifyd': 'Tradeverifyd',
  'Alixpartners': 'Alixpartners',
  'Sierra Nevada Corporation': 'Sierra Nevada Corporation',
  'Blacklane': 'Blacklane',
  'Roche Argentina': 'Roche Argentina',
  'Taman Safari Indonesia': 'Taman Safari Indonesia',
  'Brittania Industries': 'Brittania Industries',
  'Integreon': 'Integreon',
  'Withum': 'Withum',
  'Ashley Hotel Group': 'Ashley Hotel Group',
  'Protolabs': 'Protolabs',
  'MTN': 'MTN',
  'MyRepublic ID': 'MyRepublic ID',
  'WeRoad': 'WeRoad',
  'BOUNCEinc': 'BOUNCEinc',
  'Egopharm': 'Egopharm',
  'Arabian Food Supplies': 'Arabian Food Supplies',
  'Volocopter': 'Volocopter',
  'London Fire Brigade': 'London Fire Brigade',
  'Galderma': 'Galderma',
  'Gero': 'Gero',
  'Richmond Laboratories': 'Richmond Laboratories',
  'Jade Global': 'Jade Global',
  'DMS Logistics': 'DMS Logistics',
  'SalfaCorp': 'SalfaCorp',
  'Tauste': 'Tauste',
  'Puesto': 'Puesto',
  'Decathlon': 'Decathlon',
  'Hann Resorts': 'Hann Resorts',
  'Star Hotels': 'Star Hotels',
  'Go Rentals': 'Go Rentals',
  'Breezeline': 'Breezeline',
  'Treebo': 'Treebo',
  'Elsewedy Electric': 'Elsewedy Electric',
  'XeneX': 'XeneX',
  'Challenge Manufacturing': 'Challenge Manufacturing',
  'Ulta Beauty': 'Ulta Beauty',
  'Airbus': 'Airbus',
  'C2C Advanced Systems': 'C2C Advanced Systems',
  'asm': 'asm',
  'Saudi Government': 'Saudi Government',
  'United Airlines': 'United Airlines',
  'Mission Technologies (HLL)': 'Mission Technologies (HLL)',
  'IIAS, Above Space': 'IIAS, Above Space',
  'RNIB': 'RNIB',
  'Minerva Foods': 'Minerva Foods',
  'Dubai World Trade Center': 'Dubai World Trade Center',
  'Kraft Heinz': 'Kraft Heinz',
  'NCC Group': 'NCC Group',
  'H&Z Management Consulting': 'H&Z Management Consulting',
  'PureHealth': 'PureHealth',
  'Unicaja Banco': 'Unicaja Banco',
  'SkyUp Air': 'SkyUp Air',
  'Saudi Airlines': 'Saudi Airlines',
  'Wienerberger': 'Wienerberger',
  'Root': 'Root',
  'XMobots': 'XMobots',
  'British Airways': 'British Airways',
  'Sterlite Technologies': 'Sterlite Technologies',
  'Zong CMPak': 'Zong CMPak',
  'Estee Lauder': 'Estee Lauder',
  'Viasat': 'Viasat',
  'Bahrain Airport Company': 'Bahrain Airport Company',
  'GridPro': 'GridPro',
  'Swissport': 'Swissport',
  'Matrix Comsec': 'Matrix Comsec',
  'Parexel': 'Parexel',
  'Flamingo': 'Flamingo',
  'Pizza Express': 'Pizza Express',
};

async function comprehensiveEncodingFix() {
  try {
    console.log('Starting comprehensive encoding fix...');

    // Get all leads
    const leads = await prisma.lead.findMany();
    let fixedCount = 0;

    for (const lead of leads) {
      let updatedName = lead.name;
      let updatedCompany = lead.company;
      let hasChanges = false;

      // Fix name encoding issues
      if (encodingFixes[lead.name]) {
        updatedName = encodingFixes[lead.name];
        console.log(`Fixed name: "${lead.name}" -> "${updatedName}"`);
        hasChanges = true;
      }

      // Fix company encoding issues
      if (lead.company && encodingFixes[lead.company]) {
        updatedCompany = encodingFixes[lead.company];
        console.log(`Fixed company: "${lead.company}" -> "${updatedCompany}"`);
        hasChanges = true;
      }

      // Update the lead if there were changes
      if (hasChanges) {
        await prisma.lead.update({
          where: { id: lead.id },
          data: {
            name: updatedName,
            company: updatedCompany
          }
        });
        fixedCount++;
      }
    }

    console.log(`\nComprehensive encoding fix completed!`);
    console.log(`Fixed ${fixedCount} leads with encoding issues.`);

  } catch (error) {
    console.error('Error in comprehensive encoding fix:', error);
  } finally {
    await prisma.$disconnect();
  }
}

comprehensiveEncodingFix(); 